import { UserProfile, ResponderProfile, AnimalReport, AdoptionListing, AppNotification, VolunteerProfile, VolunteerDispatchRequest } from '../types';

export const INITIAL_CITIZEN_PROFILE: UserProfile = {
  id: 'usr_citizen_01',
  role: 'citizen',
  phone: '+963955654321',
  phoneVerified: true,
  fullName: 'أحمد الخطيب',
  email: 'ahmad.khatib@example.com',
  governorate: 'damascus',
  city: 'الميدان',
  neighborhood: 'حي الحقلة - جانب حديقة الميدان',
  avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
  languagePreference: 'ar',
  createdAt: '2026-05-10T10:00:00Z',
  updatedAt: '2026-05-10T10:00:00Z'
};

export const INITIAL_VOLUNTEER_PROFILES: VolunteerProfile[] = [
  {
    id: 'vol_01',
    userId: 'usr_vol_01',
    fullName: 'كرم النحاس',
    phone: '+963944112233',
    email: 'karam.nahas@gmail.com',
    governorate: 'damascus',
    city: 'المزة',
    neighborhood: 'المزة فيلات غربية - قرب مشفى المواساة',
    lat: 33.5042,
    lng: 36.2570,
    roles: ['transport', 'first_aid'],
    hasVehicle: true,
    vehicleType: 'سيارة جيب خاصة مجهزة بصندوق نقل وقفص آمن',
    experienceNote: 'حاصل على دورة إسعاف أولي بيطري من نقابة الأطباء البيطريين، ولدي خبرة 3 سنوات في نقل الحيوانات المصابة.',
    availability: 'available',
    verificationStatus: 'verified',
    totalAssistsCount: 28,
    rating: 4.9,
    createdAt: '2026-02-10T11:00:00Z'
  },
  {
    id: 'vol_02',
    userId: 'usr_vol_02',
    fullName: 'ميس الصالح',
    phone: '+963933445566',
    email: 'mays.foster@gmail.com',
    governorate: 'rif_dimashq',
    city: 'جرمانا',
    neighborhood: 'حي الحمصي - جانب ساحة النجوم',
    lat: 33.4839,
    lng: 36.3528,
    roles: ['temporary_shelter', 'other'],
    hasVehicle: false,
    shelterCapacityNote: 'غرفة هادئة ومجهزة بعوازل وشرفة آمنة، قادرة على استضافة قطتين أو 3 جراء صغيرة في فترة النقاهة بعد العمليات.',
    otherHelpDetails: 'تأمين أدوية بيطرية شائعة ومضادات حيوية وحليب جراء وقطط رضع',
    experienceNote: 'قمت باستضافة أكثر من 15 قطة بعد العمليات الجراحية حتى تماثلها للشفاء التام وتسليمها لبيوت متبنية.',
    availability: 'available',
    verificationStatus: 'verified',
    totalAssistsCount: 19,
    rating: 5.0,
    createdAt: '2026-03-05T09:30:00Z'
  },
  {
    id: 'vol_03',
    userId: 'usr_vol_03',
    fullName: 'باسل العلي',
    phone: '+963988223344',
    email: 'basel.vetaid@gmail.com',
    governorate: 'aleppo',
    city: 'الفرقان',
    neighborhood: 'دوار الشرطة - حي الفرقان',
    lat: 36.2080,
    lng: 37.1180,
    roles: ['first_aid', 'transport'],
    hasVehicle: true,
    vehicleType: 'دراجة نارية مع حقيبة إسعاف بيطرية مجهزة',
    experienceNote: 'طالب في السنة الأخيرة بكلية الطب البيطري في جامعة حلب، جاهز لتقديم إسعافات ميدانية سريعة.',
    availability: 'emergency_on_call',
    verificationStatus: 'verified',
    totalAssistsCount: 14,
    rating: 4.8,
    createdAt: '2026-04-12T14:00:00Z'
  },
  {
    id: 'vol_04',
    userId: 'usr_vol_04',
    fullName: 'ريم الخوري',
    phone: '+963966554433',
    email: 'reem.khoury.vet@gmail.com',
    governorate: 'latakia',
    city: 'اللاذقية المدينة',
    neighborhood: 'الصليبة - ساحة أوغاريت',
    lat: 35.5200,
    lng: 35.7820,
    roles: ['temporary_shelter', 'first_aid', 'other'],
    hasVehicle: true,
    vehicleType: 'سيارة متوسطة',
    shelterCapacityNote: 'حديقة منزلية أرضية مسورة بأمان، جاهزة لاستقبال حالات تحتاج حركة ونقاهة',
    otherHelpDetails: 'تصوير وتوثيق الحالات باحترافية لنشرها لحملات التبني',
    experienceNote: 'متطوعة نشطة في فرق إنقاذ الحيوانات في الساحل السوري.',
    availability: 'weekends_only',
    verificationStatus: 'verified',
    totalAssistsCount: 22,
    rating: 4.95,
    createdAt: '2026-01-20T10:00:00Z'
  },
  {
    id: 'vol_05',
    userId: 'usr_vol_05',
    fullName: 'زياد حمود',
    phone: '+963955887766',
    email: 'ziad.rescue.homs@gmail.com',
    governorate: 'homs',
    city: 'الإنشاءات',
    neighborhood: 'شارع البرازيل - جانب الحديقة',
    lat: 34.7220,
    lng: 36.6950,
    roles: ['transport', 'other'],
    hasVehicle: true,
    vehicleType: 'فان نقل صغير',
    otherHelpDetails: 'تأمين أقفاص وسلاسل نقل وصناديق إيواء آمنة',
    experienceNote: 'خبرة في نقل الحيوانات الكبيرة والمتوسطة بالتعاون مع الملاجئ.',
    availability: 'available',
    verificationStatus: 'active',
    totalAssistsCount: 11,
    rating: 4.7,
    createdAt: '2026-05-18T16:20:00Z'
  },
  {
    id: 'vol_06',
    userId: 'usr_vol_06',
    fullName: 'نور الدين غانم',
    phone: '+963944778899',
    email: 'nour.damascus.vet@gmail.com',
    governorate: 'damascus',
    city: 'الشعلان',
    neighborhood: 'شارع حافظ إبراهيم - جانب حديقة السبكي',
    lat: 33.5180,
    lng: 36.2890,
    roles: ['first_aid', 'transport'],
    hasVehicle: true,
    vehicleType: 'سيارة صغيرة مجهزة بصندوق إسعاف',
    experienceNote: 'طبيب بيطري متطوع جاهز للتدخل السريع في دمشق المركزية والمناطق المحيطة.',
    availability: 'available',
    verificationStatus: 'verified',
    totalAssistsCount: 34,
    rating: 4.98,
    createdAt: '2026-01-15T08:00:00Z'
  },
  {
    id: 'vol_07',
    userId: 'usr_vol_07',
    fullName: 'لينا البابا',
    phone: '+963933221144',
    email: 'lina.baba.foster@gmail.com',
    governorate: 'damascus',
    city: 'الميدان',
    neighborhood: 'الميدان - حي الحقلة',
    lat: 33.4930,
    lng: 36.2970,
    roles: ['temporary_shelter', 'first_aid'],
    hasVehicle: false,
    shelterCapacityNote: 'مكان دافئ ومستقل لرعاية القطط المصابة والجراء حديثة الولادة.',
    experienceNote: 'خبرة 4 سنوات في الاستضافة المؤقتة والرعاية التمريضية للحيوانات.',
    availability: 'available',
    verificationStatus: 'verified',
    totalAssistsCount: 26,
    rating: 4.92,
    createdAt: '2026-02-28T12:00:00Z'
  },
  {
    id: 'vol_08',
    userId: 'usr_vol_08',
    fullName: 'سامر قداح',
    phone: '+963999554433',
    email: 'samer.kaddah.rescue@gmail.com',
    governorate: 'damascus',
    city: 'كفرسوسة',
    neighborhood: 'كفرسوسة - قرب الشام سيتي سنتر',
    lat: 33.4980,
    lng: 36.2750,
    roles: ['transport', 'other'],
    hasVehicle: true,
    vehicleType: 'سيارة دفع رباعي مجهزة بأقفاص نقل حديدية',
    experienceNote: 'متخصص في إنقاذ ونقل الكلاب والقطط المصابة في حوادث السير على الأوتوسترادات.',
    availability: 'emergency_on_call',
    verificationStatus: 'verified',
    totalAssistsCount: 41,
    rating: 5.0,
    createdAt: '2026-01-05T15:30:00Z'
  },
  {
    id: 'vol_09',
    userId: 'usr_vol_09',
    fullName: 'يارا مراد',
    phone: '+963988665544',
    email: 'yara.murad.vet@gmail.com',
    governorate: 'damascus',
    city: 'باب توما',
    neighborhood: 'باب توما - حارة الجوانية',
    lat: 33.5140,
    lng: 36.3150,
    roles: ['first_aid', 'temporary_shelter'],
    hasVehicle: false,
    experienceNote: 'ممرضة بيطرية تقدم رعاية تمريضية مكثفة وتضميد يومي للجروح.',
    availability: 'available',
    verificationStatus: 'verified',
    totalAssistsCount: 17,
    rating: 4.88,
    createdAt: '2026-03-19T10:15:00Z'
  },
  {
    id: 'vol_10',
    userId: 'usr_vol_10',
    fullName: 'طارق عبد الله',
    phone: '+963955114477',
    email: 'tarek.qudsaya@gmail.com',
    governorate: 'rif_dimashq',
    city: 'قدسيا',
    neighborhood: 'ضاحية قدسيا - الجزيرة الرابعة',
    lat: 33.5480,
    lng: 36.2150,
    roles: ['transport', 'first_aid', 'other'],
    hasVehicle: true,
    vehicleType: 'سيارة عائلية واسعة',
    experienceNote: 'تغطية طوارئ ريف دمشق الغربي ومشروع دمر وقدسيا والمزة.',
    availability: 'available',
    verificationStatus: 'verified',
    totalAssistsCount: 23,
    rating: 4.9,
    createdAt: '2026-04-01T09:00:00Z'
  }
];

export const INITIAL_DISPATCHES: VolunteerDispatchRequest[] = [
  {
    id: 'disp_01',
    reportId: 'rep_damascus_01',
    reportReference: 'MAWA-2026-DAM-081',
    senderId: 'resp_assoc_01',
    senderName: 'جمعية رفق لحماية ورعاية الحيوان',
    senderType: 'association',
    volunteerId: 'vol_01',
    volunteerName: 'كرم النحاس',
    roleNeeded: 'transport',
    governorate: 'damascus',
    city: 'المزة',
    neighborhood: 'أوتوستراد المزة - مقابل المواساة',
    urgencyLevel: 'critical',
    message: 'نداء إسعافي عاجل: كلب مصاب برضوض في أطرافه بحاجة لنقله فوراً من موقع الحادث إلى عيادة الشفاء البيطرية في المزة فيلات.',
    status: 'accepted',
    createdAt: '2026-08-23T08:15:00Z'
  },
  {
    id: 'disp_02',
    reportId: 'rep_damascus_02',
    reportReference: 'MAWA-2026-DAM-092',
    senderId: 'resp_vet_01',
    senderName: 'د. سارة الحلبي',
    senderType: 'veterinarian',
    volunteerId: 'vol_01',
    volunteerName: 'كرم النحاس',
    roleNeeded: 'first_aid',
    governorate: 'damascus',
    city: 'الشعلان',
    neighborhood: 'شارع حافظ إبراهيم - جانب الحديقة',
    urgencyLevel: 'urgent',
    message: 'مطلوب تقديم إسعاف أولي فوري وتضميد جرح سطحي لقط مصاب وتأمينه حتى وصول سيارة العيادة.',
    status: 'completed',
    createdAt: '2026-08-22T14:20:00Z'
  },
  {
    id: 'disp_03',
    reportId: 'rep_damascus_03',
    reportReference: 'MAWA-2026-DAM-099',
    senderId: 'resp_assoc_01',
    senderName: 'جمعية رفق لحماية ورعاية الحيوان',
    senderType: 'association',
    volunteerId: 'vol_01',
    volunteerName: 'كرم النحاس',
    roleNeeded: 'transport',
    governorate: 'damascus',
    city: 'دمر',
    neighborhood: 'مشروع دمر - الجزيرة السادسة',
    urgencyLevel: 'urgent',
    message: 'مطلوب المساعدة في نقل كلب شارد تم إنقاذه من موقع خطر إلى ملجأ الرعاية المؤقتة في ريف دمشق.',
    status: 'accepted',
    createdAt: '2026-08-24T11:00:00Z'
  }
];

export const INITIAL_RESPONDER_PROFILES: ResponderProfile[] = [
  {
    id: 'resp_assoc_01',
    userId: 'usr_assoc_01',
    responderType: 'association',
    verificationStatus: 'verified',
    name: 'جمعية رفق لحماية ورعاية الحيوان',
    description: 'منظمة أهلية مرخصة متخصصة في إنقاذ الحيوانات الشاردة والمصابة، وتقديم الرعاية الطبية والإيواء وإعادة التأهيل في دمشق وريفها.',
    responsibleContactPerson: 'م. سامر البابا (مدير العمليات)',
    email: 'contact@rifq-syria.org',
    phone: '+963113322110',
    governoratesServed: ['damascus', 'rif_dimashq'],
    citiesServed: ['دمشق القديمة', 'الميدان', 'المزة', 'جرمانا', 'صحنايا', 'قدسيا'],
    servicesOffered: ['rescue', 'veterinary_care', 'shelter', 'foster', 'transport', 'spay_neuter'],
    registrationNumber: 'NGO-SY-2023-884',
    logoUrl: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?auto=format&fit=crop&w=200&q=80',
    availability: 'available',
    verifiedAt: '2026-01-15T09:00:00Z',
    createdAt: '2026-01-10T08:00:00Z'
  },
  {
    id: 'resp_vet_01',
    userId: 'usr_vet_01',
    responderType: 'veterinarian',
    verificationStatus: 'verified',
    name: 'د. سارة الحلبي',
    title: 'طبيبة وجراحة بيطرية مرخصة',
    specialty: 'جراحة العظام والأنسجة الرخوة وطب الطوارئ البيطري',
    description: 'عيادة بيطرية مجهزة بوحدة عناية مشددة، ومستعدة لاستقبال الحالات الإسعافية والجراحية للحيوانات المصابة والمنقذة.',
    email: 'dr.sara.vet@gmail.com',
    phone: '+963933987654',
    governoratesServed: ['damascus', 'rif_dimashq'],
    citiesServed: ['المزة', 'كفرسوسة', 'الصالحية', 'جرمانا'],
    servicesOffered: ['veterinary_care', 'rescue', 'spay_neuter'],
    clinicName: 'عيادة الشفاء البيطرية التخصصية',
    clinicAddress: 'دمشق - المزة فيلات غربية - جانب حديقة الجلاء',
    registrationNumber: 'SY-VET-4192',
    logoUrl: 'https://images.unsplash.com/photo-1594824813689-d4c382a93414?auto=format&fit=crop&w=200&q=80',
    availability: 'available',
    verifiedAt: '2026-02-01T12:00:00Z',
    createdAt: '2026-01-28T11:00:00Z'
  },
  {
    id: 'resp_assoc_02',
    userId: 'usr_assoc_02',
    responderType: 'association',
    verificationStatus: 'pending',
    name: 'فريق أمل لإنقاذ الحيوان - حمص',
    description: 'مبادرة تطوعية تسعى لتوثيق وإسعاف الحيوانات في محافظة حمص، بانتظار استكمال التدقيق الإداري من إدارة منصة مأوى.',
    responsibleContactPerson: 'طارق الدالاتي',
    email: 'amal.rescue.homs@gmail.com',
    phone: '+963988776655',
    governoratesServed: ['homs'],
    citiesServed: ['حمص المدينة', 'الإنشاءات', 'الوعر'],
    servicesOffered: ['rescue', 'foster', 'transport'],
    registrationNumber: 'PENDING-APP-2026-19',
    availability: 'available',
    createdAt: '2026-08-10T14:00:00Z'
  }
];

export const INITIAL_REPORTS: AnimalReport[] = [
  {
    id: 'rep_damascus_01',
    referenceNumber: 'MAWA-2026-DAM-081',
    reporterId: 'usr_citizen_01',
    reporterName: 'أحمد الخطيب',
    reporterContactName: 'أحمد الخطيب',
    reporterContactPhone: '+963955654321',
    reporterAddress: 'دمشق - حي الحقلة، جانب حديقة الميدان، بناء 14، الطابق 2',
    exactAddress: 'أوتوستراد المزة - مقابل المدخل الرئيسي لمشفى المواساة - بجانب موقف الباص',
    landmark: 'مشفى المواساة وموقف باص المزة',
    accessNotes: 'يمكن لسيارة الإسعاف التوقف مباشرة على جانب الأوتوستراد',
    stayWithAnimal: true,
    animalType: 'dog',
    animalCount: 1,
    problemCategory: 'road_accident',
    severity: 'critical',
    description: 'كلب بلدي متوسط الحجم تعرض لحادث صدم سيارة، لا يقوى على تحريك أطرافه الخلفية وينزف بشكل طفيف قرب رصيف الطريق.',
    governorate: 'damascus',
    city: 'المزة',
    neighborhood: 'أوتوستراد المزة - مقابل مشفى المواساة',
    lat: 33.5132,
    lng: 36.2625,
    approxLat: 33.5140,
    approxLng: 36.2640,
    observedAt: '2026-08-23T07:30:00Z',
    isAnimalStillThere: true,
    canReporterStayNearby: true,
    preferredContactMethod: 'phone',
    status: 'responsibility_accepted',
    isAssigned: true,
    leadResponderId: 'resp_assoc_01',
    leadResponderName: 'جمعية رفق لحماية ورعاية الحيوان',
    leadResponderType: 'association',
    leadAcceptedAt: '2026-08-23T08:00:00Z',
    assignedVolunteerId: 'vol_01',
    assignedVolunteerName: 'كرم النحاس',
    assignedVolunteerRole: 'transport',
    media: [
      {
        id: 'med_01',
        url: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=800&q=80',
        type: 'image',
        createdAt: '2026-08-23T07:35:00Z'
      }
    ],
    timeline: [
      {
        id: 'tl_01',
        reportId: 'rep_damascus_01',
        previousStatus: undefined,
        newStatus: 'submitted',
        actorId: 'usr_citizen_01',
        actorName: 'أحمد الخطيب',
        actorRole: 'citizen',
        explanation: 'تم تقديم البلاغ وتوثيق الموقع بدقة.',
        createdAt: '2026-08-23T07:35:00Z'
      },
      {
        id: 'tl_02',
        reportId: 'rep_damascus_01',
        previousStatus: 'submitted',
        newStatus: 'responsibility_accepted',
        actorId: 'usr_assoc_01',
        actorName: 'جمعية رفق لحماية ورعاية الحيوان',
        actorRole: 'responder',
        actorType: 'association',
        explanation: 'تم قبول الحالة وتوجيه سيارة الإنقاذ الميدانية فوراً إلى موقع الحادث في المزة.',
        createdAt: '2026-08-23T08:00:00Z'
      }
    ],
    publicUpdates: [
      {
        id: 'up_01',
        reportId: 'rep_damascus_01',
        authorId: 'usr_assoc_01',
        authorName: 'جمعية رفق',
        authorType: 'association',
        title: 'انطلاق فريق الطوارئ',
        content: 'فريق الإنقاذ في الطريق مزود بنقالة طبية خاصة بالكلاب الكبيرة، وسيتم التوجه مباشرة إلى العيادة البيطرية لإجراء صور شعاعية.',
        isPublic: true,
        createdAt: '2026-08-23T08:15:00Z'
      }
    ],
    createdAt: '2026-08-23T07:35:00Z',
    updatedAt: '2026-08-23T08:15:00Z'
  },
  {
    id: 'rep_aleppo_01',
    referenceNumber: 'MAWA-2026-ALP-042',
    reporterId: 'usr_citizen_02',
    reporterName: 'مريم صباغ',
    reporterContactName: 'مريم صباغ',
    reporterContactPhone: '+963944778899',
    reporterAddress: 'حلب - حي الشهباء الجديدة، شارع الكندي، بناء الوفاء',
    exactAddress: 'حلب - شارع النيل، خلف جامع الرحمن، داخل حفرة أساسات بناء قيد الإنشاء',
    landmark: 'جامع الرحمن ومدرسة النيل',
    accessNotes: 'مدخل ورشة البناء مفتوح من الشارع الفرعي الثاني',
    stayWithAnimal: false,
    animalType: 'cat',
    animalCount: 4,
    problemCategory: 'mother_babies',
    severity: 'medium',
    description: 'قطة أم ولدت 3 صغار داخل حفرة بناء مكشوفة معرضة للشمس الحارقة وخطر السقوط، تحتاج لنقل إلى مكان آمن ورعاية.',
    governorate: 'aleppo',
    city: 'الشهباء',
    neighborhood: 'شارع النيل - خلف جامع الرحمن',
    lat: 36.2160,
    lng: 37.1290,
    approxLat: 36.2170,
    approxLng: 37.1310,
    observedAt: '2026-08-22T16:00:00Z',
    isAnimalStillThere: true,
    canReporterStayNearby: false,
    preferredContactMethod: 'phone',
    status: 'waiting_responder',
    isAssigned: false,
    media: [
      {
        id: 'med_02',
        url: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80',
        type: 'image',
        createdAt: '2026-08-22T16:10:00Z'
      }
    ],
    timeline: [
      {
        id: 'tl_03',
        reportId: 'rep_aleppo_01',
        newStatus: 'submitted',
        actorId: 'usr_citizen_02',
        actorName: 'مريم صباغ',
        actorRole: 'citizen',
        explanation: 'تسجيل بلاغ قطة وصغارها.',
        createdAt: '2026-08-22T16:10:00Z'
      }
    ],
    createdAt: '2026-08-22T16:10:00Z',
    updatedAt: '2026-08-22T16:10:00Z'
  },
  {
    id: 'rep_homs_01',
    referenceNumber: 'MAWA-2026-HMS-019',
    reporterId: 'usr_citizen_03',
    reporterName: 'وسيم الجندي',
    reporterContactName: 'وسيم الجندي',
    reporterContactPhone: '+963988334455',
    reporterAddress: 'حمص - الإنشاءات، شارع البرازيل، جانب صيدلية النور',
    exactAddress: 'حمص - بساتين الغوطة الشرقية، مدخل الطريق الزراعي المؤدي لطريق تدمر القديم',
    landmark: 'مزرعة القاطرجي ومحطة الوقود المهجورة',
    accessNotes: 'طريق ترابي عريض يتسع لسيارة بيك آب أو شاحنة نقل',
    stayWithAnimal: true,
    animalType: 'horse_donkey',
    animalCount: 1,
    problemCategory: 'injured',
    severity: 'high',
    description: 'حمار يعاني من جروح غائرة في الظهر والساق اليسرى وعرج شديد، متروك بجانب مدخل بستان قديم.',
    governorate: 'homs',
    city: 'الإنشاءات',
    neighborhood: 'بساتين الغوطة الشرقية بحمص',
    lat: 34.7290,
    lng: 36.7020,
    approxLat: 34.7300,
    approxLng: 36.7050,
    observedAt: '2026-08-23T06:00:00Z',
    isAnimalStillThere: true,
    canReporterStayNearby: true,
    preferredContactMethod: 'phone',
    status: 'waiting_responder',
    isAssigned: false,
    media: [
      {
        id: 'med_03',
        url: 'https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?auto=format&fit=crop&w=800&q=80',
        type: 'image',
        createdAt: '2026-08-23T06:15:00Z'
      }
    ],
    timeline: [
      {
        id: 'tl_04',
        reportId: 'rep_homs_01',
        newStatus: 'submitted',
        actorId: 'usr_citizen_03',
        actorName: 'وسيم الجندي',
        actorRole: 'citizen',
        createdAt: '2026-08-23T06:15:00Z'
      }
    ],
    createdAt: '2026-08-23T06:15:00Z',
    updatedAt: '2026-08-23T06:15:00Z'
  },
  {
    id: 'rep_latakia_01',
    referenceNumber: 'MAWA-2026-LTK-007',
    reporterId: 'usr_citizen_04',
    reporterName: 'نور إسماعيل',
    reporterContactName: 'نور إسماعيل',
    reporterContactPhone: '+963933119922',
    reporterAddress: 'اللاذقية - حي الصليبة، شارع بغداد، جانب مدرسة الثورة',
    exactAddress: 'اللاذقية - مشروع الزراعة، قرب دوار الزراعة، خلف المجمع التجاري للاتصالات',
    landmark: 'دوار الزراعة والمجمع التجاري',
    accessNotes: 'القط تحت شجرة صغيرة داخل الحديقة الخلفية للمجمع',
    stayWithAnimal: false,
    animalType: 'cat',
    animalCount: 1,
    problemCategory: 'sick',
    severity: 'medium',
    description: 'قط شيرازي ضال يعاني من التهاب شديد في كلتا العينين وصعوبة في التنفس وفقدان شهية.',
    governorate: 'latakia',
    city: 'مشروع الزراعة',
    neighborhood: 'قرب دوار الزراعة - خلف المجمع التجاري',
    lat: 35.5380,
    lng: 35.7980,
    approxLat: 35.5390,
    approxLng: 35.8000,
    observedAt: '2026-08-21T18:00:00Z',
    isAnimalStillThere: true,
    canReporterStayNearby: false,
    preferredContactMethod: 'phone',
    status: 'receiving_veterinary_care',
    isAssigned: true,
    leadResponderId: 'resp_vet_01',
    leadResponderName: 'د. سارة الحلبي',
    leadResponderType: 'veterinarian',
    leadAcceptedAt: '2026-08-21T19:30:00Z',
    media: [
      {
        id: 'med_04',
        url: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=800&q=80',
        type: 'image',
        createdAt: '2026-08-21T18:15:00Z'
      }
    ],
    timeline: [
      {
        id: 'tl_05',
        reportId: 'rep_latakia_01',
        newStatus: 'submitted',
        actorId: 'usr_citizen_04',
        actorName: 'نور إسماعيل',
        actorRole: 'citizen',
        createdAt: '2026-08-21T18:15:00Z'
      },
      {
        id: 'tl_06',
        reportId: 'rep_latakia_01',
        previousStatus: 'submitted',
        newStatus: 'receiving_veterinary_care',
        actorId: 'usr_vet_01',
        actorName: 'د. سارة الحلبي',
        actorRole: 'responder',
        actorType: 'veterinarian',
        explanation: 'تم إدخال القط للعيادة وبدء كورس مضادات حيوية وتنظيف العيون ووضعه تحت الملاحظة.',
        createdAt: '2026-08-21T19:30:00Z'
      }
    ],
    createdAt: '2026-08-21T18:15:00Z',
    updatedAt: '2026-08-21T19:30:00Z'
  },
  {
    id: 'rep_damascus_02',
    referenceNumber: 'MAWA-2026-DAM-092',
    reporterId: 'usr_citizen_01',
    reporterName: 'سناء خوري',
    reporterContactName: 'سناء خوري',
    reporterContactPhone: '+963966221144',
    reporterAddress: 'دمشق - حي الشعلان، شارع حافظ إبراهيم',
    exactAddress: 'دمشق - الشعلان، جانب حديقة السبكي، قرب كشك بيع الكتب',
    landmark: 'حديقة السبكي',
    accessNotes: 'يمكن الوصول بالدراجة النارية أو مشياً بسهولة',
    stayWithAnimal: true,
    animalType: 'cat',
    animalCount: 1,
    problemCategory: 'injured',
    severity: 'medium',
    description: 'قط سيامي صغير مصاب بجرح قطعي في كف قدمه ينزف، تم تقديم إسعاف أولي وتطهير وتضميد بواسطة المتطوع كرم النحاس ونقله للمتابعة البيطرية.',
    governorate: 'damascus',
    city: 'الشعلان',
    neighborhood: 'شارع حافظ إبراهيم - جانب الحديقة',
    lat: 33.5200,
    lng: 36.2900,
    approxLat: 33.5210,
    approxLng: 36.2910,
    observedAt: '2026-08-22T14:00:00Z',
    isAnimalStillThere: true,
    canReporterStayNearby: true,
    preferredContactMethod: 'phone',
    status: 'receiving_veterinary_care',
    isAssigned: true,
    leadResponderId: 'resp_vet_01',
    leadResponderName: 'د. سارة الحلبي',
    leadResponderType: 'veterinarian',
    leadAcceptedAt: '2026-08-22T14:15:00Z',
    assignedVolunteerId: 'vol_01',
    assignedVolunteerName: 'كرم النحاس',
    assignedVolunteerRole: 'first_aid',
    media: [
      {
        id: 'med_dam_02',
        url: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=800&q=80',
        type: 'image',
        createdAt: '2026-08-22T14:05:00Z'
      }
    ],
    timeline: [
      {
        id: 'tl_dam_02_1',
        reportId: 'rep_damascus_02',
        newStatus: 'submitted',
        actorId: 'usr_citizen_01',
        actorName: 'سناء خوري',
        actorRole: 'citizen',
        createdAt: '2026-08-22T14:05:00Z'
      },
      {
        id: 'tl_dam_02_2',
        reportId: 'rep_damascus_02',
        previousStatus: 'submitted',
        newStatus: 'receiving_veterinary_care',
        actorId: 'usr_vet_01',
        actorName: 'د. سارة الحلبي',
        actorRole: 'responder',
        actorType: 'veterinarian',
        explanation: 'قام المتطوع كرم النحاس بتقديم الإسعاف الأولي الميداني ونقله للعيادة لإتمام الخياطة الجراحية.',
        createdAt: '2026-08-22T14:30:00Z'
      }
    ],
    createdAt: '2026-08-22T14:05:00Z',
    updatedAt: '2026-08-22T14:30:00Z'
  },
  {
    id: 'rep_damascus_03',
    referenceNumber: 'MAWA-2026-DAM-099',
    reporterId: 'usr_citizen_01',
    reporterName: 'حسام نجار',
    reporterContactName: 'حسام نجار',
    reporterContactPhone: '+963933887711',
    reporterAddress: 'دمشق - مشروع دمر، الجزيرة 6',
    exactAddress: 'دمشق - مشروع دمر، الجزيرة السادسة، جانب المجمع التجاري للجزيرة',
    landmark: 'مجمع الجزيرة السادسة التجاري',
    accessNotes: 'الكلب آمن بجوار مدخل الحديقة المجاورة',
    stayWithAnimal: true,
    animalType: 'dog',
    animalCount: 1,
    problemCategory: 'shelter_needed',
    severity: 'medium',
    description: 'جرو صغير تائه معرض لمخاطر الطريق، تم التنسيق مع المتطوع كرم لنقله إلى مركز الاستضافة المؤقتة.',
    governorate: 'damascus',
    city: 'دمر',
    neighborhood: 'مشروع دمر - الجزيرة السادسة',
    lat: 33.5350,
    lng: 36.2350,
    approxLat: 33.5360,
    approxLng: 36.2360,
    observedAt: '2026-08-24T10:45:00Z',
    isAnimalStillThere: true,
    canReporterStayNearby: true,
    preferredContactMethod: 'phone',
    status: 'responsibility_accepted',
    isAssigned: true,
    leadResponderId: 'resp_assoc_01',
    leadResponderName: 'جمعية رفق لحماية ورعاية الحيوان',
    leadResponderType: 'association',
    leadAcceptedAt: '2026-08-24T11:00:00Z',
    assignedVolunteerId: 'vol_01',
    assignedVolunteerName: 'كرم النحاس',
    assignedVolunteerRole: 'transport',
    media: [
      {
        id: 'med_dam_03',
        url: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=800&q=80',
        type: 'image',
        createdAt: '2026-08-24T10:50:00Z'
      }
    ],
    timeline: [
      {
        id: 'tl_dam_03_1',
        reportId: 'rep_damascus_03',
        newStatus: 'submitted',
        actorId: 'usr_citizen_01',
        actorName: 'حسام نجار',
        actorRole: 'citizen',
        createdAt: '2026-08-24T10:50:00Z'
      }
    ],
    createdAt: '2026-08-24T10:50:00Z',
    updatedAt: '2026-08-24T11:00:00Z'
  }
];

export const INITIAL_ADOPTIONS: AdoptionListing[] = [
  {
    id: 'ad_01',
    publisherId: 'usr_assoc_01',
    publisherName: 'جمعية رفق لحماية الحيوان',
    publisherRole: 'responder',
    publisherType: 'association',
    name: 'زعتر (Zaatar)',
    animalType: 'dog',
    breed: 'كلب بلدي سوري مهجن',
    sex: 'male',
    ageGroup: 'young',
    estimatedAge: 'سنة واحدة',
    size: 'medium',
    healthCondition: 'بصحة ممتازة، شفي تماماً من إصابة سابقة في قدمه بعد إعادة التأهيل.',
    isVaccinated: true,
    isNeutered: true,
    specialNeeds: 'لا يوجد، مفعم بالحيوية ونشيط جداً.',
    isUrgent: false,
    personality: ['ودود جداً', 'يحب اللعب', 'مطيع', 'وفي'],
    description: 'زعتر كلب وفي وذكي للغاية، تم إنقاذه في ريف دمشق قبل 6 أشهر، يحب مرافقة العائلة في المشي والتنزه ومؤدب جداً داخل المنزل.',
    goodWithChildren: true,
    goodWithCats: true,
    goodWithDogs: true,
    governorate: 'damascus',
    city: 'دمشق',
    photos: [
      'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&w=800&q=80'
    ],
    status: 'published',
    applicationsCount: 2,
    publishedAt: '2026-08-15T10:00:00Z',
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-15T10:00:00Z'
  },
  {
    id: 'ad_02',
    publisherId: 'usr_citizen_01',
    publisherName: 'أحمد الخطيب',
    publisherRole: 'citizen',
    name: 'سكر ولوز (Sugar & Almond)',
    animalType: 'cat',
    breed: 'شيرازي مهجن مع بلدي',
    sex: 'female',
    ageGroup: 'baby',
    estimatedAge: '3 أشهر',
    size: 'small',
    healthCondition: 'نظيفة ومفطومة ومتعودة على صندوق الرمل.',
    isVaccinated: true,
    isNeutered: false,
    specialNeeds: 'تفضل البقاء مع أختها إن أمكن.',
    isUrgent: true,
    personality: ['هادئة', 'لعوبة', 'لطيفة'],
    description: 'قطتان جميلتان وذكيتان تم إنقاذهما والاعتناء بهما منذ الولادة، تبحثان عن بيت هادئ ومحب في دمشق أو ريفها.',
    goodWithChildren: true,
    goodWithCats: true,
    goodWithDogs: false,
    governorate: 'damascus',
    city: 'الميدان',
    photos: [
      'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1548247416-ec66f4900b2e?auto=format&fit=crop&w=800&q=80'
    ],
    status: 'published',
    applicationsCount: 1,
    publishedAt: '2026-08-20T12:00:00Z',
    createdAt: '2026-08-20T12:00:00Z',
    updatedAt: '2026-08-20T12:00:00Z'
  },
  {
    id: 'ad_03',
    publisherId: 'usr_vet_01',
    publisherName: 'د. سارة الحلبي',
    publisherRole: 'responder',
    publisherType: 'veterinarian',
    name: 'ميشو (Misho)',
    animalType: 'cat',
    breed: 'قط تركي أنجورا أبيض',
    sex: 'male',
    ageGroup: 'adult',
    estimatedAge: 'سنتان ونصف',
    size: 'medium',
    healthCondition: 'معقم، ملقح دورياً، أجرى فحص دم شامل وكل الوظائف سليمة.',
    isVaccinated: true,
    isNeutered: true,
    specialNeeds: 'أصم جزئياً ولكن يعتمد على البصر والتفاعل الحركي ببراعة.',
    isUrgent: false,
    personality: ['حنون جداً', 'هادئ', 'يحب النوم في الأحضان'],
    description: 'ميشو قط مميز أبيض الفرو وناعم، يحب التواصل مع أصحابه ويبحث عن أسرة تقدر خصوصيته وتمنحه الأمان.',
    goodWithChildren: true,
    goodWithCats: true,
    goodWithDogs: true,
    governorate: 'damascus',
    city: 'المزة',
    photos: [
      'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=800&q=80'
    ],
    status: 'published',
    applicationsCount: 3,
    publishedAt: '2026-08-18T09:00:00Z',
    createdAt: '2026-08-18T09:00:00Z',
    updatedAt: '2026-08-18T09:00:00Z'
  }
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif_01',
    userId: 'usr_citizen_01',
    type: 'responsibility_accepted',
    titleAr: 'تم قبول مسؤولية بلاغك الإسعافي',
    titleFr: 'Prise en charge de votre signalement',
    bodyAr: 'قامت جمعية رفق لحماية الحيوان بقبول بلاغك رقم MAWA-2026-DAM-081 وتوجيه فريق الإنقاذ.',
    bodyFr: 'L’association Rifq a pris en charge votre signalement MAWA-2026-DAM-081.',
    relatedReportId: 'rep_damascus_01',
    isRead: false,
    createdAt: '2026-08-23T08:00:00Z'
  },
  {
    id: 'notif_02',
    userId: 'usr_assoc_01',
    type: 'urgent_report_nearby',
    titleAr: '🚨 بلاغ إسعافي حرج في نطاق خدمتكم',
    titleFr: '🚨 Signalement critique dans votre zone',
    bodyAr: 'تم تسجيل حادث دهس كلب في المزة بدمشق بحاجة ماسة لإسعاف فوري.',
    bodyFr: 'Accident de la route impliquant un chien à Al-Mezzeh (Damas).',
    relatedReportId: 'rep_damascus_01',
    isRead: true,
    createdAt: '2026-08-23T07:36:00Z'
  },
  {
    id: 'notif_03',
    userId: 'usr_vol_01',
    type: 'volunteer_dispatch_request',
    titleAr: '🚨 نداء استجابة عاجل: مطلوب نقل وإسعاف كلب مصاب',
    titleFr: '🚨 Demande d’intervention urgente: Transport requis',
    bodyAr: 'أرسلت لك جمعية رفق لحماية الحيوان طلباً لنقل كلب مصاب في منطقة المزة بدمشق إلى العيادة البيطرية على وجه السرعة.',
    bodyFr: 'L’association Rifq a sollicité votre aide pour le transport d’un chien blessé à Mezzeh.',
    relatedReportId: 'rep_damascus_01',
    isRead: false,
    createdAt: '2026-08-23T08:05:00Z'
  },
  {
    id: 'notif_04',
    userId: 'usr_vol_01',
    type: 'case_resolved',
    titleAr: '✅ إنجاز مهمة إنقاذ وتحديث السجل',
    titleFr: '✅ Mission de sauvetage accomplie',
    bodyAr: 'تم استكمال علاج الحالة بنجاح ونقل الحيوان إلى مركز الاستضافة المؤقتة. تمت إضافة نقطة إنجاز جديدة في سجلك التطوعي 🌟',
    bodyFr: 'Le sauvetage a été finalisé avec succès. Une nouvelle assistance a été ajoutée à votre profil.',
    relatedReportId: 'rep_damascus_01',
    isRead: true,
    createdAt: '2026-08-23T14:30:00Z'
  },
  {
    id: 'notif_05',
    userId: 'usr_vol_01',
    type: 'volunteer_welcome',
    titleAr: 'مرحباً بك في شبكة متطوعي منصة مأوى 🤝',
    titleFr: 'Bienvenue dans le réseau de bénévoles MAWA',
    bodyAr: 'تم توثيق حسابك كمتطوع ميداني معتمد في دمشق (المزة). ستصلك نداءات الجمعيات والأطباء البيطريين مباشرة هنا.',
    bodyFr: 'Votre profil de bénévole est activé. Vous recevrez toutes les alertes et missions sur ce tableau de bord.',
    isRead: true,
    createdAt: '2026-08-20T10:00:00Z'
  }
];
